require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# グローバル設定
use_modular_headers!
use_frameworks! :linkage => :static

target 'Brawl' do
  config = use_native_modules!

  # Firebase関連のPods
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  
  # Google Ads
  pod 'Google-Mobile-Ads-SDK'
  
  # gRPC関連
  pod 'gRPC-C++', :modular_headers => true
  pod 'gRPC-Core', :modular_headers => true
  
  # Gesture Handler と Reanimated
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler', :modular_headers => true
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated', :modular_headers => true
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BrawlTests' do
    inherit! :complete
  end

  post_install do |installer|
    # React Native の post install 処理
    react_native_post_install(installer, config[:reactNativePath])
    
    # ビルド設定の調整
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        
        # Split Viewサポートのための設定
        config.build_settings['SUPPORTS_MACCATALYST'] = 'YES'
        config.build_settings['SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD'] = 'YES'
        config.build_settings['SUPPORTED_PLATFORMS'] = 'iphoneos iphonesimulator'
        
        # M1 Mac対応
        if config.name == 'Debug'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
        else
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        end
      end
    end
  end
end